Add safe way to detach nodes
makeup-js/makeup-keyboard-trap pull request #9
Opened 2018-11-02 15:41 UTC by darkwebdev

In some situations we get an error ```NotFoundError: Node was not found``` on Firefox or ```noindex.js:60 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.``` on Chrome.

This happens for some reason because we try to detach a child of non-existent parent. By making detaching safe (just check if the parentNode exists) solves the problem.

2018-11-06 14:42 UTC, darkwebdev commented
@ianmcburnie @seangates guys could you please review the PR when you have time?

2018-11-06 23:28 UTC, seangates requested changes
Pretty minor, but is less aggressive test strings. 😉

2018-11-06 23:28 UTC, seangates commented on test/index.js
> +    describe('given trap is active, but someone messed up the DOM', function() {
`given trap is active, but the DOM has changed`

2018-11-06 23:28 UTC, seangates commented on test/index.js
> +            it('it should not blow up in our face', function() {
`it should not throw an error`

2018-11-07 11:23 UTC, darkwebdev commented
fixed

Sean, you're boring ;)

2018-11-08 19:21 UTC, seangates commented
I know. 😞

2018-11-08 19:33 UTC, seangates approved these changes

2018-11-09 00:18 UTC, ianmcburnie approved these changes
Nice set of changes! Thanks @darkwebdev (and @seangates for reviewing).

2018-11-09 00:19 UTC, merged

2018-11-09 00:51 UTC, ianmcburnie commented
Published in v1.0.1